#include<iostream>
#include <ostream>
#include<string>
#include<fstream>
using namespace std;
    

int main()
{

char x,y,z;
int i;
x = y = z = 0;

    string path = "out.txt";
    ofstream fout;
    fout.open(path);

        if (!fout.is_open()) 
            {
                cout << "Faild to open file.Error:U suck in code" << endl;
            }
        else 
        {
            fout << "200 \ngenerated by NIKO_inc";
            
            for (i = 1; i < 199; i++) {
                
                x = x + 1.270826;
                y = y + -0.839598;
            }
            fout << "\nС        " << x << "        " << y << "        " << z << endl;
        }

        fout.close();

    return 0;

}