#include<iostream>
#include<string>
#include<fstream>
using namespace std;
    

int main()
{

double x,y,z;
int i;
x = y = z = 0;

    std::cout << std::fixed;
    std::cout << std::setprecision(6);

    string path = "out.xyz";
    ofstream fout;
    fout.open(path);

        if (!fout.is_open()) 
            {
                cout << "Faild to open file.Error:U suck in code" << endl;
            }
        else 
        {
            fout << "200 \ngenerated by NIKO_inc https://github.com/nikoincc";
            fout << "\n C         0.000000        0.000000        0.000000";
            
            for (i = 1; i < 101; i++) {
                
                x = x + 1.270826;
                y = y + -0.839598;
            
            fout << fixed << setprecision(6) << "\n С         " << x << "        " << y << "        " << z;
            
                x = x + 1.253097;
                y = y + 0.865836;
            
            fout << fixed << setprecision(6) << "\n С         " << x << "        " << y << "        " << z;
            }
        }



        fout.close();

    return 0;

}